version: "3.9"
services:
  admin:
    image: "mashupbranding/mashup-server-admin:${TAG:-latest}"
    ports:
      - "8090:8090"
      - "5005:5005"
    volumes:
      - "${SPRING_LOG_DIR}:/logs"
    environment:
      - "JAVA_OPTS=${JAVA_OPTS}"
      - "SCOUTER_HOST=${SCOUTER_HOST}"
      - "SCOUTER_OBJECT_NAME=${SCOUTER_OBJECT_NAME}"
  recruit:
    image: "mashupbranding/mashup-server-api:${TAG:-latest}"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "${SPRING_LOG_DIR}:/logs"
    environment:
      - "JAVA_OPTS=${JAVA_OPTS}"
      - "SCOUTER_HOST=${SCOUTER_HOST}"
      - "SCOUTER_OBJECT_NAME=${SCOUTER_OBJECT_NAME}"
  filebeat:
    image: "mashupbranding/mashup-server-filebeat:${TAG:-latest}"
    volumes:
      - "${NGINX_ACCESS_LOG_PATH}:${NGINX_ACCESS_LOG_PATH}"
      - "${NGINX_ERROR_LOG_PATH}:${NGINX_ERROR_LOG_PATH}"
      - "${SPRING_LOG_DIR}:${SPRING_LOG_DIR}"
      - "${FILEBEAT_EXTERNAL_DIR}:${FILEBEAT_INTERNAL_DIR}:rw"
    environment:
      - "NGINX_ACCESS_LOG_PATH=${NGINX_ACCESS_LOG_PATH}"
      - "NGINX_ERROR_LOG_PATH=${NGINX_ERROR_LOG_PATH}"
      - "SPRING_LOG_PATH=${SPRING_LOG_PATH}"
      - "SERVICE_NAME=${SERVICE_NAME}"
      - "ES_HOST=${ES_HOST}"
      - "ES_USERNAME=${ES_USERNAME}"
      - "ES_PASSWORD=${ES_PASSWORD}"
