spring:
  datasource:
    url: ENC(CU9+Gd4ksHJLJzPuaQ48me75Ndn3+a6DJCJno6gRZm/eErglhkiTotYkEgHweDwzf5OjOUXi6t8pYODNHWGfj0GxGoJu/G3ouXPkzGNBKHAnfR4/LSEpkiUM7/OnPwzEVdL1yXAy2tbqRye5Oj/74WOiVawkxID1k5clgyKIBvsChm/N1mKbxTuz5DEgvT4w5SS9zLq5u87x1y8L3YVl0uPd635iIjydMkcw5r8qDpSrNFWV4QakN8R1GaaSUCOw8BCF/ankfmKIasm1/gfeva11LPw0CYK42cFXBIlAo9VRlNLTSFmlizGtHBZo+XZIe+YLxgbiENi1NKCV1pJ0WIfyVffRhKZD4wHGv3X8StDEH6tfkokKoPRe7jmBBL4bQJvdcpSgIO9BxK4e3fbMKw==)
    username: ENC(Rafn9TDh8A6A5mzzpMR509WKULNRrIpZM1PD89gigZNui0NEwE55dkwz/goQzQjp)
    password: ENC(fxWrJBvyF3X7SoFrGYKbeA4nLuchRIXTbaMahilpJFBSRc28VSLo6BN6PV+W/DVF)
  jpa:
    hibernate:
      ddl-auto: none
sms:
  toast:
    url: https://api-sms.cloud.toast.com/
    app-key: ENC(XX49s5+8kEqOLhg67J89qHjeXYwbU55vcqScbgECJe/u3O77Cxy1J1lz3WiPDru4tl0SUIhwG0bJze5Z+T59PQ==)
    secret-key: ENC(RxnWUTWTXS93vSfsLX0M4gHYbFGrLsFU5BH09V4Ds0bBgWcNteRYKbgVOuPe+2Si)
logging:
  config: classpath:logback/logback-spring.xml

aws:
  access-key: ENC(lZmgx3mTPaE2hvXN9vvSkhEM4TNJrcmmQNiI5wxCZJ4)
  secret-key: ENC(rEP6l0XY+8rwnd4BAMox+kY7EULBXaBoKNJinQ0VBr2pIPUzc24atCWV9k0kpLVmtfsjkvI6bls=)