spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
    #  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/recruit?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: root
    #    password: 1234
#    jpa:
#      hibernate:
#        ddl-auto: update
#      open-in-view: false
#      properties:
#        hibernate:
#          default_batch_fetch_size: 1000
sms:
  toast:
    url: https://api-sms.cloud.toast.com/
    app-key: ENC(XX49s5+8kEqOLhg67J89qHjeXYwbU55vcqScbgECJe/u3O77Cxy1J1lz3WiPDru4tl0SUIhwG0bJze5Z+T59PQ==)
    secret-key: ENC(RxnWUTWTXS93vSfsLX0M4gHYbFGrLsFU5BH09V4Ds0bBgWcNteRYKbgVOuPe+2Si)
logging:
  config: classpath:logback/logback-spring.xml
