spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
sms:
  toast:
    url: https://api-sms.cloud.toast.com/
    app-key: ENC(XX49s5+8kEqOLhg67J89qHjeXYwbU55vcqScbgECJe/u3O77Cxy1J1lz3WiPDru4tl0SUIhwG0bJze5Z+T59PQ==)
    secret-key: ENC(RxnWUTWTXS93vSfsLX0M4gHYbFGrLsFU5BH09V4Ds0bBgWcNteRYKbgVOuPe+2Si)
logging:
  config: classpath:logback/logback-spring.xml
aws:
  ses:
    access-key: ENC(aQntk9Wm8gCrHsIvt+q7+cIDTGI6hWIlRisZXE3q/BNACqKQXrXnpzrgnhHIpeALhhAe82v0niu93NTZyomkwQ==)
    secret-key: ENC(/B1+2Mflsgv1enwFvvmdzffHKGM0F6MV/Of6hdLyE+f6zkDI25TF8Av502lO0cV7PeYKdHje0FJPo22idqzsVQaRN1QM9cqvHbs1hgudDkE=)