name: Mash-Up develop Admin Server Deploy

on:
  push:
    branches: [ develop ]
    paths:
      - "mashup-admin/**"
      - "mashup-domain/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push DockerImage
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./mashup-admin/Dockerfile
          push: true
          tags: mashupbranding/mashup-server-admin:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EC2
        uses: actions/checkout@v2

      - name: Connect EC2 and Deploy
        env:
          HOST_NAME: ${{ secrets.DEV_ADMIN_AWS_HOST_NAME }}
          PRIVATE_KEY: ${{ secrets.DEV_AWS_PRIVATE_KEY }}
          USER_NAME: ${{ secrets.AWS_USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && sudo chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i "private_key" ${USER_NAME}@${HOST_NAME} '
            sh ./apps/mashup-admin/bin/deploy-docker.sh
          '
